In [1]:
import tensorflow as tf
import glob
import imageio
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
from tensorflow.keras import layers
import time
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from IPython import display
import random
from sklearn.decomposition import PCA
from sklearn.metrics import precision_recall_fscore_support,accuracy_score

In [157]:
model='DCGAN'

In [158]:
scoreD_a=np.load('./'+model+'_score/ownerA/score_ownerA.npy',allow_pickle=True)
labelD_a=np.load('./'+model+'_score/ownerA/label_ownerA.npy',allow_pickle=True)

In [159]:
scoreD_b=np.load('./'+model+'_score/ownerB/score_ownerB.npy',allow_pickle=True)
labelD_b=np.load('./'+model+'_score/ownerB/label_ownerB.npy',allow_pickle=True)

In [160]:
scoreD_c=np.load('./'+model+'_score/ownerC/score_ownerC.npy',allow_pickle=True)
labelD_c=np.load('./'+model+'_score/ownerC/label_ownerC.npy',allow_pickle=True)

In [161]:
scoreD_d=np.load('./'+model+'_score/ownerD/score_ownerD.npy',allow_pickle=True)
labelD_d=np.load('./'+model+'_score/ownerD/label_ownerD.npy',allow_pickle=True)

In [162]:
from sklearn.metrics import precision_recall_fscore_support,accuracy_score
precisiona = np.empty([scoreD_a.shape[0]-1])
recalla = np.empty([scoreD_a.shape[0]-1])
f1a = np.empty([scoreD_a.shape[0]-1])
acca = np.empty([scoreD_a.shape[0]-1])
for i in range (scoreD_a.shape[0]-1):
    precisiona[i], recalla[i], f1a[i], _ = precision_recall_fscore_support(labelD_a, scoreD_a[i+1], average='binary')
    acca[i] = accuracy_score(labelD_a, scoreD_a[i+1])

In [163]:
from sklearn.metrics import precision_recall_fscore_support,accuracy_score
precisionb = np.empty([scoreD_b.shape[0]-1])
recallb = np.empty([scoreD_b.shape[0]-1])
f1b = np.empty([scoreD_b.shape[0]-1])
accb = np.empty([scoreD_b.shape[0]-1])
for i in range (scoreD_b.shape[0]-1):
    precisionb[i], recallb[i], f1b[i], _ = precision_recall_fscore_support(labelD_b, scoreD_b[i+1], average='binary')
    accb[i] = accuracy_score(labelD_b, scoreD_b[i+1])

In [164]:
from sklearn.metrics import precision_recall_fscore_support,accuracy_score
precisionc = np.empty([scoreD_c.shape[0]-1])
recallc = np.empty([scoreD_c.shape[0]-1])
f1c = np.empty([scoreD_c.shape[0]-1])
accc = np.empty([scoreD_c.shape[0]-1])
for i in range (scoreD_c.shape[0]-1):
    precisionc[i], recallc[i], f1c[i], _ = precision_recall_fscore_support(labelD_c, scoreD_c[i+1], average='binary')
    accc[i] = accuracy_score(labelD_c, scoreD_c[i+1])

In [165]:
from sklearn.metrics import precision_recall_fscore_support,accuracy_score
precisiond = np.empty([scoreD_d.shape[0]-1])
recalld = np.empty([scoreD_d.shape[0]-1])
f1d = np.empty([scoreD_d.shape[0]-1])
accd = np.empty([scoreD_d.shape[0]-1])
for i in range (scoreD_d.shape[0]-1):
    precisiond[i], recalld[i], f1d[i], _ = precision_recall_fscore_support(labelD_d, scoreD_d[i+1], average='binary')
    accd[i] = accuracy_score(labelD_d, scoreD_d[i+1])

In [166]:
np.mean(precisiond[10:])

0.9999818722346584

In [167]:
np.mean(recalld[10:])

0.9968941398180698

In [168]:
np.mean(f1d[10:])

0.9984145292144795

In [169]:
np.mean(accd[10:])

0.9974784262103261

In [170]:
recalld

array([0.85499946, 1.        , 1.        , 1.        , 0.99952887,
       1.        , 0.88348494, 0.90051825, 1.        , 0.98510492,
       0.99934766, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.96959374, 1.        , 1.        ])

In [171]:
(np.mean(precisiona[5:])+np.mean(precisionc[5:])+np.mean(precisiond[5:]))/3

0.9948986002808673

In [172]:
(np.mean(recalla[5:])+np.mean(recallc[5:])+np.mean(recalld[5:]))/3

0.9934946719543046

In [173]:
(np.mean(f1a[5:])+np.mean(f1c[5:])+np.mean(f1d[5:]))/3

0.9940322199187298

In [174]:
(np.mean(acca[5:])+np.mean(accc[5:])+np.mean(accd[5:]))/3

0.9899991387406354

In [111]:
precisiona

array([0.88021196, 1.        , 1.        , 0.99982144, 0.99940505,
       0.99955372, 0.99949322, 0.99123713, 0.99027295, 0.98182243,
       0.98872767, 0.98611641, 0.98630298, 0.97890443, 0.97822036,
       0.97317653, 0.98343188, 0.98196592, 0.98196592, 0.96942675])

In [81]:
precisionc

array([0.87375542, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.99976008, 0.99531259,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [82]:
precisiond

array([0.73024283, 1.        , 1.        , 0.9998859 , 0.99984708,
       0.99956638, 0.99996273, 0.99732136, 0.94864443, 1.        ,
       0.99941239, 0.97872173, 0.99757157, 0.97194741, 0.99952979,
       1.        , 1.        , 1.        , 0.94531125, 0.99152934])

In [83]:
recalla

array([0.55908441, 0.9414216 , 0.9770806 , 0.96725801, 0.9658888 ,
       0.98240862, 0.98383736, 0.97749732, 0.97100845, 0.96047148,
       0.96157281, 0.95969758, 0.95276223, 0.93764139, 0.93344446,
       0.93043815, 0.92758066, 0.92466365, 0.92228241, 0.91960352])

In [84]:
recallb

array([0.71268603, 0.79053377, 0.73658414, 0.93335003, 0.92852032,
       0.93968231, 0.93216943, 0.92411992, 0.92100744, 0.91717945,
       0.89954207, 0.89725243, 1.        , 1.        , 1.        ,
       1.        , 0.99803234, 1.        , 0.99695907, 1.        ])

In [85]:
recallc

array([0.55016948, 0.82145964, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [86]:
recalld

array([0.59942739, 0.8469177 , 0.94440619, 0.95274164, 0.94784909,
       0.91896495, 0.97227558, 0.99851412, 0.68350669, 1.        ,
       0.98622839, 0.90182293, 0.98256804, 0.80110898, 0.77037654,
       0.94186931, 1.        , 0.99159207, 0.64335157, 0.69996013])

In [78]:
f1a

array([0.69684097, 0.96513633, 0.98680295, 0.98304418, 0.98235098,
       0.98775962, 0.98733459, 0.98475194, 0.98152606, 0.97598451,
       0.97561344, 0.97415213, 0.97033725, 0.96302411, 0.96131445,
       0.95988086, 0.95846341, 0.95702403, 0.95584039, 0.9544626 ])

In [59]:
f1c

array([0.870058  , 0.96704667, 0.70889801, 0.49547387, 0.87672558,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.99777023, 0.977381  , 0.95554345])

In [60]:
f1d

array([0.66308174, 0.93724631, 0.92967417, 0.94932432, 0.95844028,
       0.92615073, 0.94437883, 0.92878406, 0.95694897, 0.98416521,
       0.97826087, 0.95847811, 0.97626423, 0.95144272, 0.97057943,
       0.96955148, 0.97630887, 0.97552908, 0.94997309, 0.97433342])

In [137]:
accb

array([0.84670003, 0.49124083, 0.98259807, 0.98204516, 0.65670469,
       0.94919101, 0.95148993, 0.95917239, 0.96644745, 0.9336515 ,
       0.94607729, 0.90711209, 0.60650681, 0.37789547, 0.31972413,
       0.53099174, 0.63831335, 0.58433244, 0.40938191, 0.87932138])